/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all devices */
        get: operations["get_devices_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all devices as a map from bus info to device */
        get: operations["get_device_map_api_devices_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/configure_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configure a stream */
        post: operations["configure_stream_api_devices_configure_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/set_nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a device nickname */
        post: operations["set_nickname_api_devices_set_nickname_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/set_uvc_control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a UVC control */
        post: operations["set_uvc_control_api_devices_set_uvc_control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/add_follower": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a device as a follower to another device */
        post: operations["add_follower_api_devices_add_follower_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/remove_follower": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a device as a follower to another device */
        post: operations["remove_follower_api_devices_remove_follower_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/restart_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart a stream */
        post: operations["restart_stream_api_devices_restart_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/external/notify_camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Notify dweOS that a camera has been configured externally */
        post: operations["notify_camera_api_devices_external_notify_camera_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/save_preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Preferences */
        post: operations["set_preferences_api_preferences_save_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/get_recommended_host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommended Host */
        get: operations["get_recommended_host_api_preferences_get_recommended_host_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart the system */
        post: operations["restart_api_system_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown the system */
        post: operations["shutdown_api_system_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all recordings */
        get: operations["get_recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/disk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get physical disk usage */
        get: operations["get_disk_usage_api_recordings_disk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/zip/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Zip files and generate token */
        post: operations["prepare_zip_download_api_recordings_zip_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/zip/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download ZIP using token */
        get: operations["download_zip_api_recordings_zip_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific recording */
        get: operations["get_recording_api_recordings__recording_path__get"];
        put?: never;
        post?: never;
        /** Delete a recording */
        delete: operations["delete_recording_api_recordings__recording_path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete multiple recordings */
        post: operations["bulk_delete_recording_api_recordings_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{old_name}/{new_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a recording */
        patch: operations["rename_recording_api_recordings__old_name___new_name__patch"];
        trace?: never;
    };
    "/api/network/wired/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the wired devices */
        get: operations["get_wired_devices_api_network_wired_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network/connection_profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the connection profiles */
        get: operations["get_connection_profiles_api_network_connection_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network/update_connection_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update the profile of a given nmconnection */
        post: operations["update_connection_profile_api_network_update_connection_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/network/wired/activate_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a given profile for a device */
        post: operations["activate_profile_api_network_wired_activate_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pwm/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frequency */
        get: operations["get_frequency_api_pwm_frequency_get"];
        put?: never;
        /** Set Frequency */
        post: operations["set_frequency_api_pwm_frequency_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pwm/apply_from_fps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply From Fps */
        post: operations["apply_from_fps_api_pwm_apply_from_fps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supported features */
        get: operations["_lambda__api_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFollowerPayload */
        AddFollowerPayload: {
            /** Leader Bus Info */
            leader_bus_info: string;
            /** Follower Bus Info */
            follower_bus_info: string;
        };
        /** CameraModel */
        CameraModel: {
            /** Path */
            path: string;
            /** Formats */
            formats: {
                [key: string]: components["schemas"]["FormatSizeModel"][];
            };
        };
        /** ConnectionProfileModel */
        ConnectionProfileModel: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            ipv4_settings: components["schemas"]["IPV4Configuration"];
        };
        /** ControlFlagsModel */
        ControlFlagsModel: {
            /** Default Value */
            default_value: number | boolean;
            /**
             * Max Value
             * @default 0
             */
            max_value: number;
            /**
             * Min Value
             * @default 0
             */
            min_value: number;
            /**
             * Step
             * @default 0
             */
            step: number;
            control_type: components["schemas"]["ControlTypeEnum"];
            /** Menu */
            menu?: components["schemas"]["MenuItemModel"][];
        };
        /** ControlModel */
        ControlModel: {
            flags: components["schemas"]["ControlFlagsModel"];
            /** Control Id */
            control_id: number;
            /** Name */
            name: string;
            /** Value */
            value: number | boolean;
        };
        /**
         * ControlTypeEnum
         * @enum {string}
         */
        ControlTypeEnum: "INTEGER" | "BOOLEAN" | "MENU" | "BUTTON" | "INTEGER64" | "CTRL_CLASS" | "STRING" | "BITMASK" | "INTEGER_MENU";
        /** DeviceDescriptorModel */
        DeviceDescriptorModel: {
            /** Bus Info */
            bus_info: string;
        };
        /** DeviceInfoModel */
        DeviceInfoModel: {
            /** Device Name */
            device_name: string;
            /** Bus Info */
            bus_info: string;
            /** Device Paths */
            device_paths: string[];
            /** Vid */
            vid: number;
            /** Pid */
            pid: number;
        };
        /** DeviceModel */
        DeviceModel: {
            /** Cameras */
            cameras?: components["schemas"]["CameraModel"][] | null;
            /** Controls */
            controls: components["schemas"]["ControlModel"][];
            stream: components["schemas"]["StreamModel"];
            /** Name */
            name?: string | null;
            /** Vid */
            vid: number;
            /** Pid */
            pid: number;
            /** Bus Info */
            bus_info: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Nickname */
            nickname: string;
            device_info?: components["schemas"]["DeviceInfoModel"] | null;
            device_type: components["schemas"]["DeviceType"];
            /**
             * Followers
             * @default []
             */
            followers: string[];
            /**
             * Is Managed
             * @default false
             */
            is_managed: boolean;
            /** @default {
             *       "num_drops": 0
             *     } */
            frame_stats: components["schemas"]["FrameDropStats"];
            /**
             * Is Externally Managed
             * @default false
             */
            is_externally_managed: boolean;
            /**
             * String3
             * @default
             */
            string3: string;
        };
        /** DeviceNicknameModel */
        DeviceNicknameModel: {
            /** Bus Info */
            bus_info: string;
            /** Nickname */
            nickname: string;
        };
        /**
         * DeviceState
         * @description Device State
         *
         *     * UNKNOWN
         *     * UNMANAGED
         *     * UNAVAILABLE
         *     * DISCONNECTED
         *     * PREPARE
         *     * CONFIG
         *     * NEED_AUTH
         *     * IP_CONFIG
         *     * IP_CHECK
         *     * SECONDARIES
         *     * ACTIVATED
         *     * DEACTIVATING
         *     * FAILED
         * @enum {integer}
         */
        DeviceState: 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 | 110 | 120;
        /**
         * DeviceType
         * @description Device type Enum
         * @enum {integer}
         */
        DeviceType: 0 | 1 | 2 | 3 | 4;
        /** DiskStatsResponse */
        DiskStatsResponse: {
            /** Total */
            total: number;
            /** Used */
            used: number;
            /** Free */
            free: number;
        };
        /** FeatureSupport */
        FeatureSupport: {
            /** Ttyd */
            ttyd: boolean;
            /** Wifi */
            wifi: boolean;
            /** Serial */
            serial: boolean;
        };
        /** FormatSizeModel */
        FormatSizeModel: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Intervals */
            intervals: components["schemas"]["IntervalModel"][];
        };
        /** FrameDropStats */
        FrameDropStats: {
            /** Num Drops */
            num_drops: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IPV4Address */
        IPV4Address: {
            /** Address */
            address: string;
            /** Prefix */
            prefix: number;
        };
        /** IPV4Configuration */
        IPV4Configuration: {
            /** Ip Addresses */
            ip_addresses?: components["schemas"]["IPV4Address"][] | null;
            /** Gateway */
            gateway?: string | null;
            /** @default unknown */
            method: components["schemas"]["IPV4Method"];
            /** Dns */
            dns?: string[] | null;
            /** Never Default */
            never_default?: boolean | null;
        };
        /**
         * IPV4Method
         * @enum {string}
         */
        IPV4Method: "manual" | "auto" | "unknown";
        /** IntervalModel */
        IntervalModel: {
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
        };
        /** LogSchema */
        LogSchema: {
            /** Timestamp */
            timestamp: string;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Lineno */
            lineno: number;
            /** Function */
            function: string;
            /** Message */
            message: string;
        };
        /**
         * ManagedEvent
         * @enum {string}
         */
        ManagedEvent: "DEVICE_MANAGED" | "STREAM_START" | "STREAM_STOP";
        /** ManagedNotifyModel */
        ManagedNotifyModel: {
            /** Bus Info */
            bus_info: string;
            event: components["schemas"]["ManagedEvent"];
        };
        /** MenuItemModel */
        MenuItemModel: {
            /** Index */
            index: number;
            /** Name */
            name: string;
        };
        /** RecordingInfo */
        RecordingInfo: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Format */
            format: string;
            /** Duration */
            duration: string;
            /** Size */
            size: string;
            /** Created */
            created: string;
        };
        /** SavedPreferencesModel */
        SavedPreferencesModel: {
            /** @default {
             *       "host": "192.168.2.1",
             *       "port": 5600
             *     } */
            default_stream: components["schemas"]["StreamEndpointModel"] | null;
            /**
             * Suggest Host
             * @default true
             */
            suggest_host: boolean;
            /**
             * Frequency Offset
             * @default 0
             */
            frequency_offset: number;
        };
        /** SimpleRequestStatusModel */
        SimpleRequestStatusModel: {
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /**
         * StreamEncodeTypeEnum
         * @enum {string}
         */
        StreamEncodeTypeEnum: "MJPG" | "H264" | "SOFTWARE_H264" | "NONE";
        /** StreamEndpointModel */
        StreamEndpointModel: {
            /** Host */
            host: string;
            /** Port */
            port: number;
        };
        /** StreamFormatModel */
        StreamFormatModel: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            interval: components["schemas"]["IntervalModel"];
        };
        /** StreamInfoModel */
        StreamInfoModel: {
            /** Bus Info */
            bus_info: string;
            stream_type: components["schemas"]["StreamTypeEnum"];
            stream_format: components["schemas"]["StreamFormatModel"];
            encode_type: components["schemas"]["StreamEncodeTypeEnum"];
            /** Enabled */
            enabled: boolean;
            /** Endpoints */
            endpoints: components["schemas"]["StreamEndpointModel"][];
        };
        /** StreamModel */
        StreamModel: {
            /** Device Path */
            device_path: string;
            encode_type: components["schemas"]["StreamEncodeTypeEnum"];
            stream_type: components["schemas"]["StreamTypeEnum"];
            /** Endpoints */
            endpoints: components["schemas"]["StreamEndpointModel"][];
            /** Width */
            width: number;
            /** Height */
            height: number;
            interval: components["schemas"]["IntervalModel"];
            /** Enabled */
            enabled: boolean;
        };
        /**
         * StreamTypeEnum
         * @enum {string}
         */
        StreamTypeEnum: "UDP" | "RECORDING";
        /** UVCControlModel */
        UVCControlModel: {
            /** Bus Info */
            bus_info: string;
            /** Control Id */
            control_id: number;
            /** Value */
            value: number | boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WiredDeviceModel */
        WiredDeviceModel: {
            /** Interface */
            interface: string;
            state: components["schemas"]["DeviceState"];
            /** Is Active */
            is_active: boolean;
            /** Active Profile Id */
            active_profile_id?: string | null;
            active_ip_configuration?: components["schemas"]["IPV4Configuration"] | null;
            /** Available Profiles */
            available_profiles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_devices_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceModel"][];
                };
            };
        };
    };
    get_device_map_api_devices_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["DeviceModel"];
                    };
                };
            };
        };
    };
    configure_stream_api_devices_configure_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamInfoModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_nickname_api_devices_set_nickname_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceNicknameModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_uvc_control_api_devices_set_uvc_control_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UVCControlModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_follower_api_devices_add_follower_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFollowerPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_follower_api_devices_remove_follower_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFollowerPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_stream_api_devices_restart_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceDescriptorModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notify_camera_api_devices_external_notify_camera_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagedNotifyModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPreferencesModel"];
                };
            };
        };
    };
    set_preferences_api_preferences_save_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedPreferencesModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommended_host_api_preferences_get_recommended_host_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    restart_api_system_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
        };
    };
    shutdown_api_system_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleRequestStatusModel"];
                };
            };
        };
    };
    get_logs_api_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogSchema"][];
                };
            };
        };
    };
    get_recordings_api_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingInfo"][];
                };
            };
        };
    };
    get_disk_usage_api_recordings_disk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskStatsResponse"];
                };
            };
        };
    };
    prepare_zip_download_api_recordings_zip_prepare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_zip_api_recordings_zip_download_get: {
        parameters: {
            query: {
                token: string;
                filename?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_recordings__recording_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recording_api_recordings__recording_path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_recording_api_recordings_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_recording_api_recordings__old_name___new_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                old_name: string;
                new_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wired_devices_api_network_wired_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WiredDeviceModel"][];
                };
            };
        };
    };
    get_connection_profiles_api_network_connection_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionProfileModel"][];
                };
            };
        };
    };
    update_connection_profile_api_network_update_connection_profile_post: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IPV4Configuration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_profile_api_network_wired_activate_profile_post: {
        parameters: {
            query: {
                interface: string;
                profile_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frequency_api_pwm_frequency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    set_frequency_api_pwm_frequency_post: {
        parameters: {
            query: {
                frequency: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_from_fps_api_pwm_apply_from_fps_post: {
        parameters: {
            query: {
                fps: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _lambda__api_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSupport"];
                };
            };
        };
    };
}
