/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all devices */
        get: operations["get_devices_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/sync_groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of the synchronization groups */
        get: operations["get_sync_groups_devices_sync_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/set_sync_group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a camera to a sync group (will create a new one if it does not already exist) */
        post: operations["set_sync_group_devices_set_sync_group_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/configure_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Configure a stream */
        post: operations["configure_stream_devices_configure_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/set_nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a device nickname */
        post: operations["set_nickname_devices_set_nickname_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/set_uvc_control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a UVC control */
        post: operations["set_uvc_control_devices_set_uvc_control_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/restart_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart a stream */
        post: operations["restart_stream_devices_restart_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/save_preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Preferences */
        post: operations["set_preferences_preferences_save_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences/get_recommended_host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommended Host */
        get: operations["get_recommended_host_preferences_get_recommended_host_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart the system */
        post: operations["restart_system_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown the system */
        post: operations["shutdown_system_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lights */
        get: operations["get_lights_lights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lights/set_intensity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Intensity */
        post: operations["set_intensity_lights_set_intensity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all recordings */
        get: operations["get_recordings_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific recording */
        get: operations["get_recording_recordings__recording_path__get"];
        put?: never;
        post?: never;
        /** Delete a recording */
        delete: operations["delete_recording_recordings__recording_path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{old_name}/{new_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a recording */
        patch: operations["rename_recording_recordings__old_name___new_name__patch"];
        trace?: never;
    };
    "/recording/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download all recordings as a zip file */
        get: operations["zip_recordings_recording_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supported features */
        get: operations["_lambda__features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CameraModel */
        CameraModel: {
            /** Path */
            path: string;
            /** Formats */
            formats: {
                [key: string]: components["schemas"]["FormatSizeModel"][];
            };
        };
        /** ControlFlagsModel */
        ControlFlagsModel: {
            /** Default Value */
            default_value: number;
            /** Max Value */
            max_value: number;
            /** Min Value */
            min_value: number;
            /** Step */
            step: number;
            control_type: components["schemas"]["ControlTypeEnum"];
            /** Menu */
            menu?: components["schemas"]["MenuItemModel"][];
        };
        /** ControlModel */
        ControlModel: {
            flags: components["schemas"]["ControlFlagsModel"];
            /** Control Id */
            control_id: number;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /**
         * ControlTypeEnum
         * @enum {string}
         */
        ControlTypeEnum: "INTEGER" | "BOOLEAN" | "MENU" | "BUTTON" | "INTEGER64" | "CTRL_CLASS" | "STRING" | "BITMASK" | "INTEGER_MENU";
        /** DeviceDescriptorModel */
        DeviceDescriptorModel: {
            /** Bus Info */
            bus_info: string;
        };
        /** DeviceInfoModel */
        DeviceInfoModel: {
            /** Device Name */
            device_name: string;
            /** Bus Info */
            bus_info: string;
            /** Device Paths */
            device_paths: string[];
            /** Vid */
            vid: number;
            /** Pid */
            pid: number;
        };
        /** DeviceModel */
        DeviceModel: {
            /** Cameras */
            cameras?: components["schemas"]["CameraModel"][] | null;
            /** Controls */
            controls: components["schemas"]["ControlModel"][];
            stream: components["schemas"]["StreamModel"];
            /** Name */
            name?: string | null;
            /** Vid */
            vid: number;
            /** Pid */
            pid: number;
            /** Bus Info */
            bus_info: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Nickname */
            nickname: string;
            device_info?: components["schemas"]["DeviceInfoModel"] | null;
            device_type: components["schemas"]["DeviceType"];
            /**
             * Is Managed
             * @default false
             */
            is_managed: boolean;
            /** Sync Group */
            sync_group?: string | null;
        };
        /** DeviceNicknameModel */
        DeviceNicknameModel: {
            /** Bus Info */
            bus_info: string;
            /** Nickname */
            nickname: string;
        };
        /**
         * DeviceType
         * @description Device type Enum
         * @enum {integer}
         */
        DeviceType: 0 | 1 | 2 | 3 | 4;
        /** FeatureSupport */
        FeatureSupport: {
            /** Ttyd */
            ttyd: boolean;
            /** Wifi */
            wifi: boolean;
        };
        /** FormatSizeModel */
        FormatSizeModel: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Intervals */
            intervals: components["schemas"]["IntervalModel"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntervalModel */
        IntervalModel: {
            /** Numerator */
            numerator: number;
            /** Denominator */
            denominator: number;
        };
        /** Light */
        Light: {
            /** Intensity */
            intensity: number;
            /** Pin */
            pin: number;
            /** Nickname */
            nickname: string;
            /** Controller Index */
            controller_index: number;
            /** Controller Name */
            controller_name: string;
        };
        /** LogSchema */
        LogSchema: {
            /** Timestamp */
            timestamp: string;
            /** Level */
            level: string;
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Lineno */
            lineno: number;
            /** Function */
            function: string;
            /** Message */
            message: string;
        };
        /** MenuItemModel */
        MenuItemModel: {
            /** Index */
            index: number;
            /** Name */
            name: string;
        };
        /** RecordingInfo */
        RecordingInfo: {
            /** Path */
            path: string;
            /** Name */
            name: string;
            /** Format */
            format: string;
            /** Duration */
            duration: string;
            /** Size */
            size: string;
            /** Created */
            created: string;
        };
        /** SavedPreferencesModel */
        SavedPreferencesModel: {
            /** @default {
             *       "host": "192.168.2.1",
             *       "port": 5600
             *     } */
            default_stream: components["schemas"]["StreamEndpointModel"] | null;
            /**
             * Suggest Host
             * @default true
             */
            suggest_host: boolean;
        };
        /** SetLightInfo */
        SetLightInfo: {
            /** Index */
            index: number;
            /** Intensity */
            intensity: number;
        };
        /**
         * StreamEncodeTypeEnum
         * @enum {string}
         */
        StreamEncodeTypeEnum: "MJPG" | "H264" | "SOFTWARE_H264";
        /** StreamEndpointModel */
        StreamEndpointModel: {
            /** Host */
            host: string;
            /** Port */
            port: number;
        };
        /** StreamFormatModel */
        StreamFormatModel: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            interval: components["schemas"]["IntervalModel"];
        };
        /** StreamInfoModel */
        StreamInfoModel: {
            /** Bus Info */
            bus_info: string;
            stream_type: components["schemas"]["StreamTypeEnum"];
            stream_format: components["schemas"]["StreamFormatModel"];
            encode_type: components["schemas"]["StreamEncodeTypeEnum"];
            /** Enabled */
            enabled: boolean;
            /** Endpoints */
            endpoints: components["schemas"]["StreamEndpointModel"][];
        };
        /** StreamModel */
        StreamModel: {
            /** Device Path */
            device_path: string;
            encode_type: components["schemas"]["StreamEncodeTypeEnum"];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Fps */
            fps: number;
        };
        /**
         * StreamTypeEnum
         * @enum {string}
         */
        StreamTypeEnum: "UDP" | "RECORDING";
        /** SyncGroupModel */
        SyncGroupModel: {
            /** Bus Info */
            bus_info: string;
            /** Group */
            group: string;
        };
        /** UVCControlModel */
        UVCControlModel: {
            /** Bus Info */
            bus_info: string;
            /** Control Id */
            control_id: number;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_devices_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceModel"][];
                };
            };
        };
    };
    get_sync_groups_devices_sync_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    set_sync_group_devices_set_sync_group_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncGroupModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_stream_devices_configure_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamInfoModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_nickname_devices_set_nickname_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceNicknameModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_uvc_control_devices_set_uvc_control_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UVCControlModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_stream_devices_restart_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceDescriptorModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedPreferencesModel"];
                };
            };
        };
    };
    set_preferences_preferences_save_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedPreferencesModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommended_host_preferences_get_recommended_host_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    restart_system_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shutdown_system_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_lights_lights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Light"][];
                };
            };
        };
    };
    set_intensity_lights_set_intensity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLightInfo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogSchema"][];
                };
            };
        };
    };
    get_recordings_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingInfo"][];
                };
            };
        };
    };
    get_recording_recordings__recording_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recording_recordings__recording_path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_recording_recordings__old_name___new_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                old_name: string;
                new_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    zip_recordings_recording_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    _lambda__features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureSupport"];
                };
            };
        };
    };
}
