export const TOUR_STEP_IDS = {
  POWER_SWITCH: "power-switch",
  WIFI_SWITCH: "wifi-switch",
  ETHERNET_SWITCH: "thernet-switch",
  HELP_SWITCH: "help-switch",
  MODE_TOGGLE: "mode-toggle",
  CAMERAS: "cameras",
  DEMO_DEVICE: "demo-device",
  DEVICE_NAME: "device-name",
  DEVICE_STREAM_CONFIG: "device-stream-config",
  DEVICE_ENDPOINTS: "device-endpoints",
  ADD_ENDPOINTS: "add-endpoints",
  DEVICE_MODE: "device-mode",
  DEVICE_SETTINGS: "device-settings",
  DEVICE_STREAM: "device-stream",
  REC_PAGE: "rec-page",
  DEMO_RECORDING: "demo-recording",
  RECORDING_FOOTER: "recording-footer",
  PREFS_PAGE: "prefs-page",
  DEFAULT_STREAM_PREFS: "default-stream-prefs",
  LOGS_PAGE: "logs-page",
  DEMO_LOGS: "demo-logs",
  TERMINAL: "terminal",
  RESET_TOUR: "reset-tour",
};
