name: Test OpenAPI Export
on:
  push:
    branches: ["feature/openapi-ci"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "Test OpenAPI export"
        run: |
          pip install -r backend_py/requirements.txt
          python3 -m backend_py.scripts.export_openapi
          cat openapi.json
